### ISSUE TITLE
Just use the already-written getPairs() method instead.

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#10]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/f1f8a44cc8aa8b275aae667c4b5b053e51ad2bb1/src/project_1/Poker.java#L72

**Comment by BoimaM** [comment]
I checked the assignment repo in Gitlab, and I did not see code for this method. I'm confused about where to find the method.
