### ISSUE TITLE
Not sure of the purpose of this else if block

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#11]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/f1f8a44cc8aa8b275aae667c4b5b053e51ad2bb1/src/project_1/Poker.java#L129

Explain in comments why it's needed.

**Comment by BoimaM** [comment]
That line makes sure the next card in the sorted hand is not the same as the current card. If they're different, it means the cards aren't in a perfect sequence, so we start counting again from 1. This helps us figure out if there's a straight in the hand.

**Comment by BoimaM** [comment]
If you don't think it is necessary, I'll just remove it.

**Comment by mu-jchung** [comment]
> That line makes sure the next card in the sorted hand is not the same as the current card. If they're different, it means the cards aren't in a perfect sequence, so we start counting again from 1. This helps us figure out if there's a straight in the hand.

If two consecutive cards in the sorted hand have the same value, then there's no possibility of a straight. The else-if is not needed.
