### ISSUE TITLE
Ace can be a part of two possible straights.

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#12]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/f1f8a44cc8aa8b275aae667c4b5b053e51ad2bb1/src/project_1/Poker.java#L119

Remember that "The Ace can either precede a 2 or follow a king."

**Comment by BoimaM** [comment]
Im confused on what the issue is here?

**Comment by BoimaM** [comment]
The code was corrected to handle Ace's.
