### ISSUE TITLE
Arrays.sort(hand) will fail until the PlayingCard class implements the java Comparable interface.

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#15]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/c6b760f4694543421fcf1ba1376511d9f9d25fa9/src/project_1/Poker.java#L22

See https://www.codecademy.com/resources/docs/java/comparable, http://rockhopper.monmouth.edu/cs/jchung/cs176/501b/comparable_sorting_files_exceptions and https://pages.cs.wisc.edu/~cs302/labs/lab14/lab14.html

If needed, I can do a Zoom tutorial on how the Comparable interface can be applied to PlayingCard.

**Comment by BoimaM** [comment]
This implementation was added PlayingCard class to fix the issue.
