### ISSUE TITLE
The getPairs() method must not detect pairs in three-of-a-kind or four-of-a-kind.

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#16]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/c6b760f4694543421fcf1ba1376511d9f9d25fa9/src/project_1/Poker.java#L21

As currently written, a hand containing three-of-a-kind would be detected as 2 pairs, and a hand containing four-of-a-kind would be detected as 3 pairs.

**Comment by BoimaM** [comment]
Code changed: 
public int getPairs(PlayingCard[] hand) {
        Arrays.sort(hand); //Sort the hand
        int pairCount = 0;
        boolean threeOfAKind = hasThreeOfAKind(hand);
        boolean fourOfAKind = hasFourOfAKind(hand);

        for (int i = 0; i < hand.length - 1; i++) {
            if (hand[i].getValue() == hand[i + 1].getValue()) {
                if ((i + 2 < hand.length && hand[i].getValue() == hand[i + 2].getValue()) || // Three of a kind
                        (i + 3 < hand.length && hand[i].getValue() == hand[i + 3].getValue())) { // Four of a kind
                    continue;
                }
                pairCount++;
                i++;
            }
        }
        if (pairCount == 0) {
            return 0; // no pairs
        } else if (pairCount == 1) {
            return 1; // one pair
        } else {
            return 2; // two pairs
        }
    }
 The code should be fixed to account for this issue.
