### ISSUE TITLE
Your hasStraight() method needs to first detect the special case of the high-Ace straight and then regular straights.

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#17]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/c6b760f4694543421fcf1ba1376511d9f9d25fa9/src/project_1/Poker.java#L119

After sorting the cards, your method should first try to detect the special-case high-Ace straight (card values 1, 10, 11, 12, 13). And then it should try to detect regular straights.

**Comment by BoimaM** [comment]
Code was changed: 
 public boolean hasStraight(PlayingCard[] hand) {
    Arrays.sort(hand);

    //Check for special-case high ace straight
    if (hand[0].getValue() == 1 &&
      hand[1].getValue() == 10 &&
      hand[2].getValue() == 11 &&
      hand[3].getValue() == 12 &&
      hand[4].getValue() == 13){
        return true;
    }
    
    int count = 1;

    for (int i = 0; i < hand.length - 1; i++){
        if (hand[i + 1].getValue() - hand[i].getValue() == 1 ||
         (hand[i].getValue() == 1 && hand[ i +1].getValue() == 10))
            count++;
        if (count == 5){
            return true;
            }
        }
    return false;
    }

This should address the issue.
