### ISSUE TITLE
You should be calling the getPairs() method in hasFullHouse()

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#18]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/a61621eaa1a4ed67d0e3c906fa91843415513d6c/src/project_1/Poker.java#L65

You should be calling the getPairs() method in hasFullHouse() to see if it returns 1 (for one pair).

Also, currently hasFullHouse() is not detecting full house correctly:

Hold on. I'm shuffling the deck.
Here is your hand:
1 - 4 of Hearts
2 - 3 of Hearts
3 - King of Clubs
4 - 4 of Clubs
5 - 5 of Diamonds
How many cards in your hand do you want to replace (0-5)?
3
Enter the number of the cards you want to replace (1-5), separated by spaces:
2 3 5
Updated hand:
1 - 4 of Hearts
2 - 4 of Spades
3 - Ace of Clubs
4 - 4 of Clubs
5 - 3 of Clubs

You have a FULL HOUSE.

**Comment by BoimaM** [comment]
![Screen Shot 2024-04-16 at 1 25 25 PM](https://github.com/BoimaM/semester_javaCourse_SP24/assets/125925952/abb9d01a-48c4-4c8b-949e-3abb5102609f)

The Full house was detected within my IDE. Above is a screenshot for proof Professor.

**Comment by mu-jchung** [comment]
A full house is three-of-a-kind plus one pair. 9-9-9-Jack-Queen is not a full house.

**Comment by BoimaM** [comment]
I'm unsure why it isn't catching, I have looked over both the getPair() and hasThreeOfAKind() methods to see if they were faulty/affecting the hasFullHouse(), but I didn't see anything. 

I'm very confused now.

**Comment by BoimaM** [comment]
public boolean hasFullHouse(PlayingCard[] hand) {
        //check for three of a kind
        boolean threeOfAKind = hasThreeOfAKind(hand);
        //Check for pair:
        int pairCount = getPairs(hand);

        return threeOfAKind && pairCount == 1;
    }
