### ISSUE TITLE
If the hand is sorted, hand[0] would be Ace, not hand[4].

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#19]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/634b981aca871c7d4371f780e0f88550289d5e6b/src/project_1/Poker.java#L150

**Comment by BoimaM** [comment]
code changed: public boolean hasRoyalFlush(PlayingCard[]hand){
        if (hasStraightFlush(hand)) {
            Arrays.sort(hand);
            if (hand[0].getValue() == 1 && hand[1].getValue() == 10 &&
                hand[2].getValue() == 11 && hand[3].getValue() == 12 &&
                hand[4].getValue() == 13) {
                return true;
            }
        }
        return false;
    }
