### ISSUE TITLE
The setHour method should just print that the hour is set to 0, not this.hour. Same comment for setMinute.

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#2]
https://github.com/BoimaM/Semester_java_course_SP24/blob/6d59f7fb6923e6ae63c8f9e0d938d05d49b571a5/src/chapter6_classes_and_objects/TimeOfDay.java#L18

**Comment by BoimaM** [comment]
Issue is resolved.
