### ISSUE TITLE
The hasThreeOfAKind() method would detect 4 of a kind as 3 of a kind.

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#20]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/634b981aca871c7d4371f780e0f88550289d5e6b/src/project_1/Poker.java#L65

This is not a problem if a program (PokerGame.java) checks for 4 of a kind before 3 of a kind, but this would not pass a unit test.

**Comment by BoimaM** [comment]
public boolean hasThreeOfAKind(PlayingCard[] hand) {
        Arrays.sort(hand);
        for (int i = 0; i < hand.length - 2; i++) {
            if (hand[i].getValue() == hand[i + 1].getValue() &&
                    hand[i].getValue() == hand[i + 2].getValue()) {
                // Check if there are no additional cards of the same rank
                if (i + 3 >= hand.length || hand[i].getValue() != hand[i + 3].getValue()) {
                    return true; // Found three of a kind
                }
            }
        }
        return false; // Not three of a kind is found.
    }
