### ISSUE TITLE
addMinute: If the minute becomes 0, then just calling addHour() should be sufficient.

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#3]
https://github.com/BoimaM/Semester_java_course_SP24/blob/6d59f7fb6923e6ae63c8f9e0d938d05d49b571a5/src/chapter6_classes_and_objects/TimeOfDay.java#L42

There should be no need to check for hour !=23, and there should be no need for the else if.

**Comment by BoimaM** [comment]
Issue is resolved
