### ISSUE TITLE
The BankAccount class getAccountInfo() method shouldn't be static and shouldn't need any input parameters.

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#6]
https://github.com/BoimaM/Semester_java_course_SP24/blob/37774489769ceabb37e4121982e682a0fe6db67e/src/chapter6_classes_and_objects/BankAccount.java#L18

**Comment by BoimaM** [comment]
Bug fixed and pushed to origin.
