### ISSUE TITLE
The second draw() method should be rewritten to return an array of PlayingCard

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#8]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/f1f8a44cc8aa8b275aae667c4b5b053e51ad2bb1/src/project_1/CardGame.java#L66

See the new definition of the draw() method #2 at https://cssegit.monmouth.edu/jchung/cs176lab/-/blob/master/share/lab_project_5/CardGame.java#L88

**Comment by BoimaM** [comment]
Issue resolved.
