### ISSUE TITLE
Just use the already-written hasThreeOfAKind‎() method instead.

### ISSUE THREAD

**Issue by mu-jchung** [BoimaM/Semester_java_course_SP24#9]
https://github.com/BoimaM/semester_javaCourse_SP24/blob/f1f8a44cc8aa8b275aae667c4b5b053e51ad2bb1/src/project_1/Poker.java#L64

**Comment by BoimaM** [comment]
I checked the assignment repo in Gitlab, and I did not see code for this method. I'm confused about where to find the method.

**Comment by mu-jchung** [comment]
> I checked the assignment repo in Gitlab, and I did not see code for this method. I'm confused about where to find the method.

You're repeating code in the hasFullHouse() method that you already wrote in the hasThreeOfAKind‎() method. You should just call the hasThreeOfAKind‎() method from the hasFullHouse() method.

**Comment by BoimaM** [comment]
Method was changed to this: 
 public boolean hasFullHouse(PlayingCard[] hand) {

        //check for three of a kind
        boolean threeOfAKind = hasThreeOfAKind(hand);

        //Check for pair:
        Arrays.sort(hand);
        boolean pair = false;
        for (int i = 0; i < hand.length - 1; i++) {
            if (hand[i].getValue() == hand[i + 1].getValue()) {
                pair = true;
                break;
            }
        }
        return threeOfAKind && pair;
    }
